In [1]:
import numpy as np
import tensorflow as tf
from keras import layers
from keras import models

Using TensorFlow backend.


In [2]:
infec = np.load('infected.npy')
uninfec = np.load('uninfected.npy')

In [6]:
model = models.Sequential()

model.add(layers.Conv2D(120,(3,3),activation='relu', input_shape=(128,128,3)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(220,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(320,(3,3),activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(320,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
directory = "C:\\Users\\Varun\\Project\\cell_images"

from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255, rotation_range=30,width_shift_range=0.2,\
                                  height_shift_range=0.2,shear_range=0.3,zoom_range=0.2)

train_generator = train_datagen.flow_from_directory(directory, target_size=(128,128), batch_size=50, class_mode='binary')
validation_generator = train_datagen.flow_from_directory(directory, target_size=(128,128),batch_size=50, class_mode='binary')

Found 27558 images belonging to 2 classes.
Found 27558 images belonging to 2 classes.


In [8]:
from keras import optimizers
model.compile(loss='binary_crossentropy',optimizer=optimizers.RMSprop(lr=1e-4),metrics=['acc'])

In [ ]:
history = model.fit_generator(train_generator, steps_per_epoch=100, epochs=30,\
                              validation_data=validation_generator,validation_steps=5)

Instructions for updating:
Use tf.cast instead.
Epoch 1/30
 54/100 [===============>..............] - ETA: 1:25 - loss: 0.7365 - acc: 0.5381

In [5]:
model.save('cnn_keras.h5')

NameError: name 'model' is not defined

In [2]:
from keras.models import load_model
model = load_model('cnn_keras.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [3]:
cd


C:\Users\Varun


In [3]:
from PIL import Image

In [5]:
im = np.array(Image.open('C:\\Users\\Varun\\Project\\cell_images\\Parasitized\\C38P3thinF_original_IMG_20150621_112116_cell_204.png'))

In [8]:
im

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [11]:
im.shape

(163, 142, 3)

In [12]:
im.reshape(1,163,142,3)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]], dtype=uint8)

In [13]:
model.predict_classes(im)

ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (163, 142, 3)

In [6]:
im = np.expand_dims(im,axis=0)

In [7]:
im.shape

(1, 121, 121, 3)

In [18]:
model.predict_classes(im)

ValueError: Error when checking input: expected conv2d_1_input to have shape (128, 128, 3) but got array with shape (163, 142, 3)

ValueError: cannot reshape array of size 69438 into shape (128,128,3)

In [20]:
img_ = Image.fromarray(im, 'RGB')
image = img_.resize((50, 50))

ValueError: Too many dimensions: 4 > 3.

In [4]:
ig = np.array(Image.open('C:\\Users\\Varun\\Project\\cell_images\\Parasitized\\C39P4thinF_original_IMG_20150622_111326_cell_22.png'))

In [5]:
img_ = Image.fromarray(ig, 'RGB')
image = img_.resize((128, 128))

In [6]:
image = np.expand_dims(image,axis=0)

In [7]:
image.shape

(1, 128, 128, 3)

In [8]:
model.predict_classes(image)

array([[0]])

In [9]:
model._make_predict_function(image)

TypeError: _make_predict_function() takes 1 positional argument but 2 were given

In [11]:
image.model._make_predict_function()

AttributeError: 'numpy.ndarray' object has no attribute 'model'

In [12]:
image = model._make_predict_function()

In [14]:
print(image)

None
